services:
  valkey:
    image: valkey/valkey:latest
    command: valkey-server --port 6379 --requirepass ${VALKEY_PASSWORD}
    hostname: "valkey"
    restart: unless-stopped
    volumes:
      - './data:/data'
  affront:
    container_name: affront
    pull_policy: build
    build: 
      context: ./affront
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 6080:6080 # host:container
  sprinkler:
    container_name: sprinkler
    pull_policy: build
    build: 
      context: ./sprinkler
      dockerfile: Dockerfile
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 6070:3000